version: '3.9'

services:

  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=dbuser'
      - 'POSTGRES_DB=authservice_db'
    ports:
      - '6432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

#  authservice:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        JAR_FILE: target/*.jar
#    environment:
#      - 'POSTGRES_PASSWORD=secret'
#      - 'POSTGRES_USER=dbuser'
#      - 'POSTGRES_DB=jdbc:postgresql://postgres:5432/authservice_db'
#    ports:
#      - '8081:8080'
#    depends_on:
#      - postgres